#ifndef GRAMMAR_H
#define GRAMMAR_H

#define KEYWORD_INPUT "INPUT"
#define KEYWORD_OUTPUT "OUTPUT"

typedef enum {
  TOKEN_NUMBER,
  TOKEN_IDENTIFIER,
  TOKEN_KEYWORD,
  TOKEN_PLUS,
  TOKEN_MINUS,
  TOKEN_MULTIPLY,
  TOKEN_DIVIDE,
  TOKEN_LPAREN,
  TOKEN_RPAREN,
  TOKEN_SEMICOLON,
  TOKEN_ERROR
} TokenType;

#endif
